name: instagram_clone
description: Instagram Clone

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Figtree
      fonts:
        - asset: fonts/Figtree-Regular.ttf
        - asset: fonts/Figtree-Italic.ttf
          style: italic
        - asset: fonts/Figtree-Bold.ttf
          weight: 700
        - asset: fonts/Figtree-BoldItalic.ttf
          style: italic
          weight: 700
